### ISSUE TITLE
Add hollow airfoil profile

### ISSUE THREAD

**Issue by wierni** [RaulBejarano/Ultimate-Toroidal-Propeller-Generator#12] opened 2023-04-06 07:37 UTC

**Comment by wierni** [comment] 2023-04-06 07:38
Add an airfoil profile, par example the hollow curve like an GWS prop for better performance

**Comment by RaulBejarano** [comment] 2023-04-10 12:51
Hi @wierni. I've answered first issue #13 that ask for the same as you. I'm going to mark this as a duplicate.

Thanks for your enhacement proposal.

**Comment by RaulBejarano** [comment] 2023-04-10 12:53
Duplicate of #13

**Closed as not planned by RaulBejarano** 2023-04-10 12:53 UTC
